# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from pearsonsubscriptionsapi.api_helper import APIHelper
from pearsonsubscriptionsapi.exceptions.api_exception import APIException
from pearsonsubscriptionsapi.models.auth_error import AuthError


class AuthErrorTypeException(APIException):
    def __init__(self, reason, response):
        """Constructor for the AuthErrorTypeException class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(AuthErrorTypeException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.auth_error = AuthError.from_dictionary(dictionary.get('authError')) if 'authError' in dictionary.keys() else None

    def __str__(self):
        base_str = super().__str__()
        return (f'{self.__class__.__name__}('
                f'{base_str[base_str.find("(") + 1:-1]}, '
                f'auth_error={self.auth_error!s})')
