# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from pearsonsubscriptionsapi.api_helper import APIHelper
from pearsonsubscriptionsapi.exceptions.api_exception import APIException
from pearsonsubscriptionsapi.models.order_resp_error import OrderRespError


class OrderRespTypeErrorException(APIException):
    def __init__(self, reason, response):
        """Constructor for the OrderRespTypeErrorException class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(OrderRespTypeErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.order_number = dictionary.get("orderNumber") if dictionary.get("orderNumber") else None
        self.subscription_id = dictionary.get("subscriptionId") if dictionary.get("subscriptionId") else None
        self.order_resp_error = OrderRespError.from_dictionary(dictionary.get('orderRespError')) if 'orderRespError' in dictionary.keys() else None

    def __str__(self):
        base_str = super().__str__()
        return (f'{self.__class__.__name__}('
                f'{base_str[base_str.find("(") + 1:-1]}, '
                f'order_number={self.order_number!s}, '
                f'subscription_id={self.subscription_id!s}, '
                f'order_resp_error={self.order_resp_error!s})')
