# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from pearsonsubscriptionsapi.api_helper import APIHelper
from pearsonsubscriptionsapi.configuration import Server
from pearsonsubscriptionsapi.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from pearsonsubscriptionsapi.http.http_method_enum import HttpMethodEnum


class HealthController(BaseController):

    """A Controller to access Endpoints in the pearsonsubscriptionsapi API."""
    def __init__(self, config):
        super(HealthController, self).__init__(config)

    def health_check(self):
        """Does a GET request to /health-check.

        TODO: type endpoint description here.

        Returns:
            mixed: Response from the API. Success

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path('/health-check')
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.dynamic_deserialize)
        ).execute()
