# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pearsonsubscriptionsapi.api_helper import APIHelper
from pearsonsubscriptionsapi.models.bill_to_contact_post_order import BillToContactPostOrder


class Account(object):

    """Implementation of the 'Account' model.

    The information of the new account to be created with the order. Note
    that this actually specifies the invoice owner account of the
    subscriptions included in this order. To create the new account,
    either a **creditCard** structure or the
    **hpmCreditCardPaymentMethodId** field (but not both) should be
    provided. The one provided becomes the default payment method for this
    account. If the credit card information is declined or can't be
    verified, then the account is not created.

    Attributes:
        account_number (str): TODO: type description here.
        additional_email_addresses (str): List of additional email addresses
            to receive emailed invoices. Values should be a comma-separated
            list of email addresses.
        customer_service_rep_name (str): Name of the account's customer
            service representative, if applicable.
        purchase_order_number (str): The number of the purchase order
            associated with this account. Purchase order information generally
            comes from customers.
        sales_rep (str): The name of the sales representative associated with
            this account, if applicable.
        sequence_set_id (str): The ID of the billing document sequence set to
            assign to the customer account.   The billing documents to
            generate for this account will adopt the prefix and starting
            document number configured in the sequence set.
        allow_invoice_edit (bool): Indicates if associated invoices can be
            edited. Values are:   * `true` * `false` (default)
        name (str): TODO: type description here.
        currency (str): 3 uppercase character currency code
        bill_cycle_day (int): Day of the month that the account prefers
            billing periods to begin on. If set to 0, the bill cycle day will
            be set as "AutoSet".
        invoice_delivery_prefs_print (bool): Specifies whether to turn on the
            invoice delivery method 'Print' for the new account. Values are:  
            * `true`. Turn on the invoice delivery method 'Print' for the new
            account. * `false` (default). Turn off the invoice delivery method
            'Print' for the new account.
        invoice_delivery_prefs_email (bool): Specifies whether to turn on the
            invoice delivery method 'Email' for the new account.  Values are: 
            * `true` (default). Turn on the invoice delivery method 'Email'
            for the new account. * `false`. Turn off the invoice delivery
            method 'Email' for the new account.
        auto_pay (bool): Specifies whether future payments are to be
            automatically billed when they are due. Possible values are
            `true`, `false`.
        payment_term (str): TODO: type description here.
        communication_profile_id (str): aaa.
        batch (str): Organizes your customer accounts into groups to optimize
            your billing and payment operations.
        invoice_template_id (str): Invoice template ID, configured in Billing
            Settings.
        debit_memo_template_id (str): The unique ID of the debit memo
            template, configured in Billing Settings.
        credit_memo_template_id (str): The unique ID of the credit memo
            template, configured in Billing Settings.
        bill_to_contact (BillToContactPostOrder): TODO: type description here.
        sold_to_contact (BillToContactPostOrder): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_number": 'accountNumber',
        "additional_email_addresses": 'additionalEmailAddresses',
        "customer_service_rep_name": 'customerServiceRepName',
        "purchase_order_number": 'purchaseOrderNumber',
        "sales_rep": 'salesRep',
        "sequence_set_id": 'sequenceSetId',
        "allow_invoice_edit": 'allowInvoiceEdit',
        "name": 'name',
        "currency": 'currency',
        "bill_cycle_day": 'billCycleDay',
        "invoice_delivery_prefs_print": 'invoiceDeliveryPrefsPrint',
        "invoice_delivery_prefs_email": 'invoiceDeliveryPrefsEmail',
        "auto_pay": 'autoPay',
        "payment_term": 'paymentTerm',
        "communication_profile_id": 'communicationProfileId',
        "batch": 'batch',
        "invoice_template_id": 'invoiceTemplateId',
        "debit_memo_template_id": 'debitMemoTemplateId',
        "credit_memo_template_id": 'creditMemoTemplateId',
        "bill_to_contact": 'billToContact',
        "sold_to_contact": 'soldToContact'
    }

    _optionals = [
        'account_number',
        'additional_email_addresses',
        'customer_service_rep_name',
        'purchase_order_number',
        'sales_rep',
        'sequence_set_id',
        'allow_invoice_edit',
        'name',
        'currency',
        'bill_cycle_day',
        'invoice_delivery_prefs_print',
        'invoice_delivery_prefs_email',
        'auto_pay',
        'payment_term',
        'communication_profile_id',
        'batch',
        'invoice_template_id',
        'debit_memo_template_id',
        'credit_memo_template_id',
        'bill_to_contact',
        'sold_to_contact',
    ]

    def __init__(self,
                 account_number=APIHelper.SKIP,
                 additional_email_addresses=APIHelper.SKIP,
                 customer_service_rep_name=APIHelper.SKIP,
                 purchase_order_number=APIHelper.SKIP,
                 sales_rep=APIHelper.SKIP,
                 sequence_set_id=APIHelper.SKIP,
                 allow_invoice_edit=False,
                 name=APIHelper.SKIP,
                 currency=APIHelper.SKIP,
                 bill_cycle_day=APIHelper.SKIP,
                 invoice_delivery_prefs_print=False,
                 invoice_delivery_prefs_email=False,
                 auto_pay=True,
                 payment_term=APIHelper.SKIP,
                 communication_profile_id=APIHelper.SKIP,
                 batch=APIHelper.SKIP,
                 invoice_template_id=APIHelper.SKIP,
                 debit_memo_template_id=APIHelper.SKIP,
                 credit_memo_template_id=APIHelper.SKIP,
                 bill_to_contact=APIHelper.SKIP,
                 sold_to_contact=APIHelper.SKIP):
        """Constructor for the Account class"""

        # Initialize members of the class
        if account_number is not APIHelper.SKIP:
            self.account_number = account_number 
        if additional_email_addresses is not APIHelper.SKIP:
            self.additional_email_addresses = additional_email_addresses 
        if customer_service_rep_name is not APIHelper.SKIP:
            self.customer_service_rep_name = customer_service_rep_name 
        if purchase_order_number is not APIHelper.SKIP:
            self.purchase_order_number = purchase_order_number 
        if sales_rep is not APIHelper.SKIP:
            self.sales_rep = sales_rep 
        if sequence_set_id is not APIHelper.SKIP:
            self.sequence_set_id = sequence_set_id 
        self.allow_invoice_edit = allow_invoice_edit 
        if name is not APIHelper.SKIP:
            self.name = name 
        if currency is not APIHelper.SKIP:
            self.currency = currency 
        if bill_cycle_day is not APIHelper.SKIP:
            self.bill_cycle_day = bill_cycle_day 
        self.invoice_delivery_prefs_print = invoice_delivery_prefs_print 
        self.invoice_delivery_prefs_email = invoice_delivery_prefs_email 
        self.auto_pay = auto_pay 
        if payment_term is not APIHelper.SKIP:
            self.payment_term = payment_term 
        if communication_profile_id is not APIHelper.SKIP:
            self.communication_profile_id = communication_profile_id 
        if batch is not APIHelper.SKIP:
            self.batch = batch 
        if invoice_template_id is not APIHelper.SKIP:
            self.invoice_template_id = invoice_template_id 
        if debit_memo_template_id is not APIHelper.SKIP:
            self.debit_memo_template_id = debit_memo_template_id 
        if credit_memo_template_id is not APIHelper.SKIP:
            self.credit_memo_template_id = credit_memo_template_id 
        if bill_to_contact is not APIHelper.SKIP:
            self.bill_to_contact = bill_to_contact 
        if sold_to_contact is not APIHelper.SKIP:
            self.sold_to_contact = sold_to_contact 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_number = dictionary.get("accountNumber") if dictionary.get("accountNumber") else APIHelper.SKIP
        additional_email_addresses = dictionary.get("additionalEmailAddresses") if dictionary.get("additionalEmailAddresses") else APIHelper.SKIP
        customer_service_rep_name = dictionary.get("customerServiceRepName") if dictionary.get("customerServiceRepName") else APIHelper.SKIP
        purchase_order_number = dictionary.get("purchaseOrderNumber") if dictionary.get("purchaseOrderNumber") else APIHelper.SKIP
        sales_rep = dictionary.get("salesRep") if dictionary.get("salesRep") else APIHelper.SKIP
        sequence_set_id = dictionary.get("sequenceSetId") if dictionary.get("sequenceSetId") else APIHelper.SKIP
        allow_invoice_edit = dictionary.get("allowInvoiceEdit") if dictionary.get("allowInvoiceEdit") else False
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        currency = dictionary.get("currency") if dictionary.get("currency") else APIHelper.SKIP
        bill_cycle_day = dictionary.get("billCycleDay") if dictionary.get("billCycleDay") else APIHelper.SKIP
        invoice_delivery_prefs_print = dictionary.get("invoiceDeliveryPrefsPrint") if dictionary.get("invoiceDeliveryPrefsPrint") else False
        invoice_delivery_prefs_email = dictionary.get("invoiceDeliveryPrefsEmail") if dictionary.get("invoiceDeliveryPrefsEmail") else False
        auto_pay = dictionary.get("autoPay") if dictionary.get("autoPay") else True
        payment_term = dictionary.get("paymentTerm") if dictionary.get("paymentTerm") else APIHelper.SKIP
        communication_profile_id = dictionary.get("communicationProfileId") if dictionary.get("communicationProfileId") else APIHelper.SKIP
        batch = dictionary.get("batch") if dictionary.get("batch") else APIHelper.SKIP
        invoice_template_id = dictionary.get("invoiceTemplateId") if dictionary.get("invoiceTemplateId") else APIHelper.SKIP
        debit_memo_template_id = dictionary.get("debitMemoTemplateId") if dictionary.get("debitMemoTemplateId") else APIHelper.SKIP
        credit_memo_template_id = dictionary.get("creditMemoTemplateId") if dictionary.get("creditMemoTemplateId") else APIHelper.SKIP
        bill_to_contact = BillToContactPostOrder.from_dictionary(dictionary.get('billToContact')) if 'billToContact' in dictionary.keys() else APIHelper.SKIP
        sold_to_contact = BillToContactPostOrder.from_dictionary(dictionary.get('soldToContact')) if 'soldToContact' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(account_number,
                   additional_email_addresses,
                   customer_service_rep_name,
                   purchase_order_number,
                   sales_rep,
                   sequence_set_id,
                   allow_invoice_edit,
                   name,
                   currency,
                   bill_cycle_day,
                   invoice_delivery_prefs_print,
                   invoice_delivery_prefs_email,
                   auto_pay,
                   payment_term,
                   communication_profile_id,
                   batch,
                   invoice_template_id,
                   debit_memo_template_id,
                   credit_memo_template_id,
                   bill_to_contact,
                   sold_to_contact)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'account_number={self.account_number!r}, '
                f'additional_email_addresses={self.additional_email_addresses!r}, '
                f'customer_service_rep_name={self.customer_service_rep_name!r}, '
                f'purchase_order_number={self.purchase_order_number!r}, '
                f'sales_rep={self.sales_rep!r}, '
                f'sequence_set_id={self.sequence_set_id!r}, '
                f'allow_invoice_edit={self.allow_invoice_edit!r}, '
                f'name={self.name!r}, '
                f'currency={self.currency!r}, '
                f'bill_cycle_day={self.bill_cycle_day!r}, '
                f'invoice_delivery_prefs_print={self.invoice_delivery_prefs_print!r}, '
                f'invoice_delivery_prefs_email={self.invoice_delivery_prefs_email!r}, '
                f'auto_pay={self.auto_pay!r}, '
                f'payment_term={self.payment_term!r}, '
                f'communication_profile_id={self.communication_profile_id!r}, '
                f'batch={self.batch!r}, '
                f'invoice_template_id={self.invoice_template_id!r}, '
                f'debit_memo_template_id={self.debit_memo_template_id!r}, '
                f'credit_memo_template_id={self.credit_memo_template_id!r}, '
                f'bill_to_contact={self.bill_to_contact!r}, '
                f'sold_to_contact={self.sold_to_contact!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'account_number={self.account_number!s}, '
                f'additional_email_addresses={self.additional_email_addresses!s}, '
                f'customer_service_rep_name={self.customer_service_rep_name!s}, '
                f'purchase_order_number={self.purchase_order_number!s}, '
                f'sales_rep={self.sales_rep!s}, '
                f'sequence_set_id={self.sequence_set_id!s}, '
                f'allow_invoice_edit={self.allow_invoice_edit!s}, '
                f'name={self.name!s}, '
                f'currency={self.currency!s}, '
                f'bill_cycle_day={self.bill_cycle_day!s}, '
                f'invoice_delivery_prefs_print={self.invoice_delivery_prefs_print!s}, '
                f'invoice_delivery_prefs_email={self.invoice_delivery_prefs_email!s}, '
                f'auto_pay={self.auto_pay!s}, '
                f'payment_term={self.payment_term!s}, '
                f'communication_profile_id={self.communication_profile_id!s}, '
                f'batch={self.batch!s}, '
                f'invoice_template_id={self.invoice_template_id!s}, '
                f'debit_memo_template_id={self.debit_memo_template_id!s}, '
                f'credit_memo_template_id={self.credit_memo_template_id!s}, '
                f'bill_to_contact={self.bill_to_contact!s}, '
                f'sold_to_contact={self.sold_to_contact!s})')
