# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pearsonsubscriptionsapi.api_helper import APIHelper
from pearsonsubscriptionsapi.models.update_or_add_product_charge_override import UpdateOrAddProductChargeOverride


class AddProduct(object):

    """Implementation of the 'addProduct' model.

    Information about an order action of type `addProduct`. 
    If you want to create a pending order through the "Add product" order
    action, and if the charge's trigger condition is `Specific Date`, you must
    set a charge number in the `chargeNumber` field for the "Add product"
    order action.

    Attributes:
        product_rate_plan_id (str): Internal identifier of the product rate
            plan that the rate plan is based on.
        update_or_add_product_charge_overrides
            (List[UpdateOrAddProductChargeOverride]): TODO: type description
            here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "product_rate_plan_id": 'productRatePlanId',
        "update_or_add_product_charge_overrides": 'updateOrAddProductChargeOverrides'
    }

    _optionals = [
        'product_rate_plan_id',
        'update_or_add_product_charge_overrides',
    ]

    def __init__(self,
                 product_rate_plan_id=APIHelper.SKIP,
                 update_or_add_product_charge_overrides=APIHelper.SKIP):
        """Constructor for the AddProduct class"""

        # Initialize members of the class
        if product_rate_plan_id is not APIHelper.SKIP:
            self.product_rate_plan_id = product_rate_plan_id 
        if update_or_add_product_charge_overrides is not APIHelper.SKIP:
            self.update_or_add_product_charge_overrides = update_or_add_product_charge_overrides 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        product_rate_plan_id = dictionary.get("productRatePlanId") if dictionary.get("productRatePlanId") else APIHelper.SKIP
        update_or_add_product_charge_overrides = None
        if dictionary.get('updateOrAddProductChargeOverrides') is not None:
            update_or_add_product_charge_overrides = [UpdateOrAddProductChargeOverride.from_dictionary(x) for x in dictionary.get('updateOrAddProductChargeOverrides')]
        else:
            update_or_add_product_charge_overrides = APIHelper.SKIP
        # Return an object of this model
        return cls(product_rate_plan_id,
                   update_or_add_product_charge_overrides)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'product_rate_plan_id={self.product_rate_plan_id!r}, '
                f'update_or_add_product_charge_overrides={self.update_or_add_product_charge_overrides!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'product_rate_plan_id={self.product_rate_plan_id!s}, '
                f'update_or_add_product_charge_overrides={self.update_or_add_product_charge_overrides!s})')
