# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CodeEnum(object):

    """Implementation of the 'Code' enum.

    Error codes.

    Attributes:
        E01: TODO: type description here.
        E40: TODO: type description here.
        E41: TODO: type description here.

    """
    E01 = 'E01'

    E40 = 'E40'

    E41 = 'E41'

