# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PeriodTypeEnum(object):

    """Implementation of the 'PeriodType' enum.

    Unit of time that the renewal term is measured in.

    Attributes:
        MONTH: TODO: type description here.
        YEAR: TODO: type description here.
        DAY: TODO: type description here.
        WEEK: TODO: type description here.

    """
    MONTH = 'Month'

    YEAR = 'Year'

    DAY = 'Day'

    WEEK = 'Week'

