# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pearsonsubscriptionsapi.api_helper import APIHelper


class RecurringFlatFee(object):

    """Implementation of the 'RecurringFlatFee' model.

    TODO: type model description here.

    Attributes:
        list_price (float): Only applicable for REDEMPTION to pass another
            price in addition to product price.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "list_price": 'listPrice'
    }

    _optionals = [
        'list_price',
    ]

    def __init__(self,
                 list_price=APIHelper.SKIP):
        """Constructor for the RecurringFlatFee class"""

        # Initialize members of the class
        if list_price is not APIHelper.SKIP:
            self.list_price = list_price 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        list_price = dictionary.get("listPrice") if dictionary.get("listPrice") else APIHelper.SKIP
        # Return an object of this model
        return cls(list_price)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'list_price={self.list_price!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'list_price={self.list_price!s})')
