# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TermTypeEnum(object):

    """Implementation of the 'TermType' enum.

    Type of the first term. If the value of this field is `TERMED`, the first
    term has a predefined duration based on the value of the `period` field.
    If the value of this field is `EVERGREEN`, the first term does not have a
    predefined duration.

    Attributes:
        TERMED: TODO: type description here.
        EVERGREEN: TODO: type description here.

    """
    TERMED = 'TERMED'

    EVERGREEN = 'EVERGREEN'

