# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UpToPeriodsTypeEnum(object):

    """Implementation of the 'UpToPeriodsType' enum.

    Unit of time that the charge duration is measured in. Only applicable if
    the value of the endDateCondition field is Fixed_Period.

    Attributes:
        BILLING_PERIODS: TODO: type description here.
        DAYS: TODO: type description here.
        WEEKS: TODO: type description here.
        MONTHS: TODO: type description here.
        YEARS: TODO: type description here.

    """
    BILLING_PERIODS = 'Billing_Periods'

    DAYS = 'Days'

    WEEKS = 'Weeks'

    MONTHS = 'Months'

    YEARS = 'Years'

