# -*- coding: utf-8 -*-

"""
pearsonsubscriptionsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pearsonsubscriptionsapi.api_helper import APIHelper
from pearsonsubscriptionsapi.models.add_product_end_date import AddProductEndDate
from pearsonsubscriptionsapi.models.customer_facing_custom_fields import CustomerFacingCustomFields
from pearsonsubscriptionsapi.models.overrides_pricing import OverridesPricing


class UpdateOrAddProductChargeOverride(object):

    """Implementation of the 'UpdateOrAddProductChargeOverride' model.

    TODO: type model description here.

    Attributes:
        product_rate_plan_charge_id (str): This is unique rate plan charge id
            respective to rate plan id. It signifies the subscription
            type,entitlementLevel,maxEntitlements,numEntitlements etc.
        customer_facing_custom_fields (CustomerFacingCustomFields): TODO: type
            description here.
        overrides_pricing (OverridesPricing): TODO: type description here.
        add_product_end_date (AddProductEndDate): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "product_rate_plan_charge_id": 'productRatePlanChargeId',
        "customer_facing_custom_fields": 'customerFacingCustomFields',
        "overrides_pricing": 'overridesPricing',
        "add_product_end_date": 'addProductEndDate'
    }

    _optionals = [
        'product_rate_plan_charge_id',
        'customer_facing_custom_fields',
        'overrides_pricing',
        'add_product_end_date',
    ]

    def __init__(self,
                 product_rate_plan_charge_id=APIHelper.SKIP,
                 customer_facing_custom_fields=APIHelper.SKIP,
                 overrides_pricing=APIHelper.SKIP,
                 add_product_end_date=APIHelper.SKIP):
        """Constructor for the UpdateOrAddProductChargeOverride class"""

        # Initialize members of the class
        if product_rate_plan_charge_id is not APIHelper.SKIP:
            self.product_rate_plan_charge_id = product_rate_plan_charge_id 
        if customer_facing_custom_fields is not APIHelper.SKIP:
            self.customer_facing_custom_fields = customer_facing_custom_fields 
        if overrides_pricing is not APIHelper.SKIP:
            self.overrides_pricing = overrides_pricing 
        if add_product_end_date is not APIHelper.SKIP:
            self.add_product_end_date = add_product_end_date 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        product_rate_plan_charge_id = dictionary.get("productRatePlanChargeId") if dictionary.get("productRatePlanChargeId") else APIHelper.SKIP
        customer_facing_custom_fields = CustomerFacingCustomFields.from_dictionary(dictionary.get('customerFacingCustomFields')) if 'customerFacingCustomFields' in dictionary.keys() else APIHelper.SKIP
        overrides_pricing = OverridesPricing.from_dictionary(dictionary.get('overridesPricing')) if 'overridesPricing' in dictionary.keys() else APIHelper.SKIP
        add_product_end_date = AddProductEndDate.from_dictionary(dictionary.get('addProductEndDate')) if 'addProductEndDate' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(product_rate_plan_charge_id,
                   customer_facing_custom_fields,
                   overrides_pricing,
                   add_product_end_date)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'product_rate_plan_charge_id={self.product_rate_plan_charge_id!r}, '
                f'customer_facing_custom_fields={self.customer_facing_custom_fields!r}, '
                f'overrides_pricing={self.overrides_pricing!r}, '
                f'add_product_end_date={self.add_product_end_date!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'product_rate_plan_charge_id={self.product_rate_plan_charge_id!s}, '
                f'customer_facing_custom_fields={self.customer_facing_custom_fields!s}, '
                f'overrides_pricing={self.overrides_pricing!s}, '
                f'add_product_end_date={self.add_product_end_date!s})')
