# -*- coding: utf-8 -*-

"""
pplussubscriptionpapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CancelResType(object):

    """Implementation of the 'CancelResType' model.

    TODO: type model description here.

    Attributes:
        message (str): Response Message

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message": 'message'
    }

    def __init__(self,
                 message=None):
        """Constructor for the CancelResType class"""

        # Initialize members of the class
        self.message = message 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        message = dictionary.get("message") if dictionary.get("message") else None
        # Return an object of this model
        return cls(message)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'message={self.message!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'message={self.message!s})')
