# -*- coding: utf-8 -*-

"""
pplussubscriptionpapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EndDateConditionEnum(object):

    """Implementation of the 'EndDateCondition' enum.

    enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date"

    Attributes:
        SUBSCRIPTION_END: TODO: type description here.
        FIXED_PERIOD: TODO: type description here.
        SPECIFIC_END_DATE: TODO: type description here.

    """
    SUBSCRIPTION_END = 'Subscription_End'

    FIXED_PERIOD = 'Fixed_Period'

    SPECIFIC_END_DATE = 'Specific_End_Date'

