# -*- coding: utf-8 -*-

"""
pplussubscriptionpapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderTypeEnum(object):

    """Implementation of the 'OrderType' enum.

    Order Type .

    Attributes:
        UPGRADE: TODO: type description here.
        DOWNGRADE: TODO: type description here.
        RENEWON: TODO: type description here.
        RENEWOFF: TODO: type description here.
        MIBUPGRADE: TODO: type description here.
        MIBRENEWON: TODO: type description here.
        MIBRENEWOFF: TODO: type description here.

    """
    UPGRADE = 'UPGRADE'

    DOWNGRADE = 'DOWNGRADE'

    RENEWON = 'RENEWON'

    RENEWOFF = 'RENEWOFF'

    MIBUPGRADE = 'MIBUPGRADE'

    MIBRENEWON = 'MIBRENEWON'

    MIBRENEWOFF = 'MIBRENEWOFF'

