# -*- coding: utf-8 -*-

"""
pplussubscriptionpapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubscriptionSourceEnum(object):

    """Implementation of the 'SubscriptionSource' enum.

    Internal or external

    Attributes:
        INTERNAL: TODO: type description here.
        ENUM_PCOM: TODO: type description here.

    """
    INTERNAL = 'Internal'

    ENUM_PCOM = 'p.com'

