# -*- coding: utf-8 -*-

"""
pplussubscriptionpapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from pplussubscriptionpapi.api_helper import APIHelper


class TermsAndConditions(object):

    """Implementation of the 'termsAndConditions' model.

    change the terms and conditions of a subscription .

    Attributes:
        autorenew (bool): autorenew flag

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "autorenew": 'autorenew'
    }

    _optionals = [
        'autorenew',
    ]

    def __init__(self,
                 autorenew=APIHelper.SKIP):
        """Constructor for the TermsAndConditions class"""

        # Initialize members of the class
        if autorenew is not APIHelper.SKIP:
            self.autorenew = autorenew 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        autorenew = dictionary.get("autorenew") if "autorenew" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(autorenew)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'autorenew={self.autorenew!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'autorenew={self.autorenew!s})')
