# -*- coding: utf-8 -*-

"""
pplussubscriptionpapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'Type' enum.

    TODO: type enum description here.

    Attributes:
        CREATESUBSCRIPTION: TODO: type description here.
        ADDPRODUCT: TODO: type description here.
        REMOVEPRODUCT: TODO: type description here.
        RENEWSUBSCRIPTION: TODO: type description here.
        TERMSANDCONDITIONS: TODO: type description here.

    """
    CREATESUBSCRIPTION = 'CreateSubscription'

    ADDPRODUCT = 'AddProduct'

    REMOVEPRODUCT = 'RemoveProduct'

    RENEWSUBSCRIPTION = 'RenewSubscription'

    TERMSANDCONDITIONS = 'TermsAndConditions'

